from MaterialEdit.fun_制作首图.layout_固定裁剪 import fun_固定裁剪
from MaterialEdit.type import _ImageItem

fun_固定裁剪(
    image_list=[
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(1).png", ratio=0.526),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(2).png", ratio=0.584),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(3).png", ratio=0.526),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(4).png", ratio=0.584),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(5).png", ratio=0.584),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(6).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(7).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(8).png", ratio=0.526),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(9).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(10).png", ratio=0.562),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(11).png", ratio=0.562),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(12).png", ratio=0.562),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(13).png", ratio=0.562),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(14).png", ratio=0.562),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(15).png", ratio=0.562),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(16).png", ratio=0.526),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(17).png", ratio=0.75),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(18).png", ratio=0.526),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(19).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(20).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(21).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(22).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(23).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(24).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(25).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(26).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(27).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(28).png", ratio=2),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(29).png", ratio=2),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(30).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(31).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(32).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(33).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(34).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(35).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(36).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(37).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(38).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(39).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(40).png", ratio=0.562),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(41).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(42).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(43).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(44).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(45).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(46).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(47).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(48).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(49).png", ratio=0.666),
        _ImageItem(path="F:/小夕素材/重阳节/预览图/小夕素材(50).png", ratio=0.666),
    ],
    line=5,
    spacing=10,
    xq_width=1500,
    xq_height=1500,
    crop_position="center",
).show()
