from .fun_上传产品到淘宝 import AutoUploadProductToTaobao
from .fun_上传素材到百度网盘 import AutoUploadMaterialToBaiduYun
from .fun_下载目录移动到素材目录 import DownPathMoveToMaterialPath
from .fun_自动生成详情 import AutoMakeProductImage
from .fun_自动素材处理 import AutoMaterialFileEdit
from .fun_获取百度网盘下载链接 import AutoGetBaiDuShareLink
